flush ruleset
table inet filter {
 chain input { type filter hook input priority 0; policy drop; iif "lo" accept; ct state established,related accept; iifname "eth1" ip saddr 10.20.0.10 tcp dport 3128 accept; tcp dport 22 accept; }
 chain forward { type filter hook forward priority 0; policy drop; }
 chain output { type filter hook output priority 0; policy accept; }
}
table ip nat { chain postrouting { type nat hook postrouting priority 100; oifname "eth0" masquerade; } }
